USE LADCH28082023;

CREATE TABLE Empleado (
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
Correo NVARCHAR(50) NOT NULL,
Puesto NVARCHAR(50) NOT NULL
);
